Update install_dependencies.yml
n

diff --git a/.github/workflows/install_dependencies.yml b/.github/workflows/install_dependencies.yml
--- a/.github/workflows/install_dependencies.yml
+++ b/.github/workflows/install_dependencies.yml
@@ -16,12 +16,19 @@ jobs:
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
-        python-version: 3.9  # Utilisation de Python 3.9
+        python-version: 3.11  # Utilisation de Python 3.11
 
     - name: Install system dependencies for TA-Lib
       run: |
         sudo apt-get update
-        sudo apt-get install -y build-essential python3-dev libatlas-base-dev libta-lib0 libta-lib-dev
+        sudo apt-get install -y build-essential python3-dev libatlas-base-dev
+        # Tentative d'installation de libta-lib-dev
+        sudo apt-get install -y libta-lib-dev || true  # Ignore error if not found
+        # Essayer d'installer TA-Lib via pip si les dépendances système échouent
+        if ! dpkg -s libta-lib-dev; then
+          echo "libta-lib-dev not found, installing TA-Lib via pip"
+          pip install TA-Lib  # Installer directement via pip
+        fi
 
     - name: Upgrade pip to the latest version
       run: |
@@ -30,7 +37,6 @@ jobs:
     - name: Install Python dependencies
       run: |
         pip install -r requirements.txt  # Installer les dépendances Python listées dans requirements.txt
-        pip install TA-Lib  # Installer TA-Lib avec pip
 
     - name: Run tests
       run: |
